version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: chatbot_backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Keep this only for development, remove in production
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: chatbot_frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    volumes:
      - .:/app  # Keep this only for development, remove in production
    command: streamlit run frontend/streamlit_app.py --server.port 8501 --server.enableCORS false --server.enableXsrfProtection false
