version: '3.8'

services:
  backend:
    build: .
    container_name: chatbot_backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Mount the entire project to the container
  frontend:
    build: .
    container_name: chatbot_frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    volumes:
      - .:/app  # Mount the entire project to the container
